### ISSUE TITLE
feature: support for multiple projects

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#11]
Support for multiple projects each with its own list of reports.

**Comment by mastbaum** [comment]
i think this is best implemented by just having separate databases, which you'd probably want anyway for auth reasons.

if you want the same interface but different templates, it's just a matter of doing something like:

```
$ egret push localhost/phila-snoplus
$ egret pushdata localhost/phila-snoplus templates_snoplus.json

$ egret push localhost/phila-miniclean
$ egret pushdata localhost/phila-miniclean templates_miniclean.json
```

etc., then use vhosts to make the urls what you really want: /snoplus/shifts, /miniclean/shifts, ...

**Comment by bobthebrewer** [comment]
Not sure, I'd like to see them well-integrated.  It would be nice if one could sign into a single site, and depending on their groups membership, immediately have access to the shift reports of all groups they belong to.

**Comment by mastbaum** [comment]
If you want access control -- i.e. users can only view reports for the certain experiments, separate databases are the only option due to limitations in couchdb. (could be implemented in middleware, but that's outside the scope of philadelphia. see rant [1] on this topic).

the solution is to use couchdb's built-in authentication (the _users database) and restrict access to each experiment's database using the "readers" list in the security options. accounts (and sessions) will be shared across all dbs.

i think you're also hinting at a sort of shift report portal ("my experiments", "my reports"), which is possible but will depend on specific needs and i think is also beyond the scope of this project. such a thing could be implemented as a design document in another database (_users, perhaps): a webpage some javascript to make ajax queries to a list of dbs to generate the lists.

[1] http://sphaleron.blogspot.com/2011/10/this-is-not-dbms-you-are-looking-for.html
