### ISSUE TITLE
feature: Auto-save

### ISSUE THREAD

**Issue by bobthebrewer** [mastbaum/philadelphia#20]
Every change to a report in progress, other than comments, starts or resets a 10-second timer.  When the timer fires, auto-save a temporary copy of the report.  Now nothing will be lost if the computer crashes, power fails, rockburst occurs directly above the computer, etc.

**Comment by mastbaum** [comment]
It currently auto-saves every 10 seconds, regardless of user interaction. I could go either way, but i like frequent-if-unnecessary updates, since if the user comes back after a while, "oh, it saved approximately now" is better than "it saved sometime around when i stopped working on it." it also saves when you leave the page.

**Comment by bobthebrewer** [comment]
Ah, once again I didn't notice it was already doing that.  I see that I can return to view an auto-saved shift report, but it's not clear if there's a way to edit it yet, but I assume that's in the pipe.
